---
version: "2.2"
services:
  marvyn-rip-disc:
    extends:
      file: base.yml
      service: marvyn-base
    hostname: marvyn
    env_file:
      - mail.env
    environment:
      - ID_CDROM_MEDIA_CD
      - ID_CDROM_MEDIA_CD_R
      - ID_CDROM_MEDIA_DVD
      - ID_CDROM_MEDIA_BD
      - ID_FS_LABEL
      - MARVYN_CD_TITLE_DEPTH=3
      - MARVYN_EJECT_DISC=no
    devices:
      - /dev/cdrom:/dev/cdrom
      - /dev/dvd:/dev/dvd
      - /dev/sg1:/dev/sg1
      - /dev/sr0:/dev/sr0
    group_add:
      - cdrom
    cap_add:
      - SYS_RAWIO
